### PR TITLE
Resolve a promise to an empty string instead of rejecting it on local theme in settings.json

### PR DESCRIPTION
**Pull request by nuno-silva18**

### CODE REVIEW

**Comment by sudodoki** [comment]
I don't think title is representing what changed in code. Maybe, you didn't push some changes?

**Comment by sudodoki** [comment]
This should fix #147.
@nuno-silva18 Can you please squash your commits? [Sample instruction](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) just in case you need one. If you can't or don't want to do that, I can do it myself.

**Comment by nuno-silva18** [comment]
@sudodoki I tried to squash the commits but I'm not sure if this is how it's supposed to look like, I'd really appreciate some help here!

**Comment by sudodoki** [comment]
Closing this in favor of https://github.com/jdan/cleaver/pull/165

**Pull request closed without merging**
