### PR TITLE
npm upgrade does not work : use update instead

### PR DESCRIPTION
**Pull request by adriens**
please see the log below to upgrade :

```
salad74@themint:~ > npm upgrade

Usage: npm <command>

where <command> is one of:
    add-user, adduser, apihelp, author, bin, bugs, c, cache,
    completion, config, ddp, dedupe, deprecate, docs, edit,
    explore, faq, find, find-dupes, get, help, help-search,
    home, i, info, init, install, isntall, issues, la, link,
    list, ll, ln, login, ls, outdated, owner, pack, prefix,
    prune, publish, r, rb, rebuild, remove, repo, restart, rm,
    root, run-script, s, se, search, set, show, shrinkwrap,
    star, stars, start, stop, submodule, tag, test, tst, un,
    uninstall, unlink, unpublish, unstar, up, update, v,
    version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /home/salad74/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@1.3.10 /usr/share/npm
```

whereas :

```
salad74@themint:~ > sudo npm update -g cleaver
npm http GET https://registry.npmjs.org/cleaver
npm http 304 https://registry.npmjs.org/cleaver
```

### CODE REVIEW

**Comment by adriens** [comment]
had some issue while trying to upgrade to latest cleaver version.

**Comment by jdan** [comment]
Thank you @adriens :dancer:

**Comment by adriens** [comment]
You're welcome. I often use your sofware, i save a lot of time thanks to it ! :+1:

**Comment by jdan** [comment]
Very glad to hear that :)

**Pull request merged**
