### PR TITLE
Fix background color issue after fullscreen

### PR DESCRIPTION
**Pull request by yielder**
Currently the background color is not working after entering fullscreen.
This code snip should fix the issue.
I only tested it for my Chrome(46.0.2490.86).

### CODE REVIEW

**Comment by jdan** [comment]
Hey @yielder,

Thanks for this - can you post a screenshot of the background color not filling the entire area? I'm on Chrome 46 on OSX and the color seems to take up the whole screen without issue.

**Comment by yielder** [comment]
To make contrast clear I changed original to red:
before enter fullscreen:
screen shot 2015-11-30 at 02 24 04
after fullscreen:
screen shot 2015-11-30 at 02 24 46
My Chrome is also on OSX btw.
Also, I need to manually add code snip like the one I requested for almost all other cleaver themes in the style.css file to make it behave normally in fullscreen mode..

**Comment by jdan** [comment]
Ah, thank you!

If that's the case, maybe we should instead move the `background-color` from `body { }` to `.slide { }` in **default.css**?

Thank you very much for pointing this out, and yeah I definitely missed it without changing the color to red first.

**Comment by yielder** [comment]
Moving the background-color from body { } to .slide { } in default.css also works.
It seems simpler~

**Comment by jdan** [comment]
Woohoo - thanks again :star2: !

**Pull request merged**
